url: https://y7kim.github.io
baseurl: /huwelijk/

# Site settings
title: Lies & Sander
email: sandervandecruys@gmail.com
description: "Bruiloftsite."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: bb5844
  secondary: E6AC27  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Lies Mesens
  pic: 1
  position: de bruid
  social:
    - title: envelope
      url: mailto:liesmesens@gmail.com
    - title: facebook
      url: https://www.facebook.com/lies.mesens
    - title: instagram
      url: https://instagram.com/liesmesens/

- name: Sander Van de Cruys
  pic: 2
  position: de bruidegom
  social:
    - title: envelope
      url: mailto:sandervandecruys@gmail.com
    - title: facebook
      url: https://www.facebook.com/sander.vandecruys/
    - title: instagram
      url: https://instagram.com/sandvdc

- name: Tinne Mesens
  pic: 3
  position: Getuige van de bruid
  social:
    - title: envelope
      url: #
    - title: facebook
      url: https://www.facebook.com/tinne.mesens.7
    - title: instagram
      url: https://instagram.com/tinnemesens/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
